// Datos iniciales generados a partir de los catálogos en Excel/CSV de MOCCA Accesorios.
// Se usan una sola vez desde la herramienta de carga inicial (ver src/firebase/seed.js).

export const categoriasSeed = [
  { id: "caimanes", nombre: "Caimanes", prefijo: "CAI" },
  { id: "cinturones", nombre: "Cinturones", prefijo: "CIN" },
  { id: "bolsos", nombre: "Bolsos", prefijo: "BOL" },
  { id: "pulseras", nombre: "Pulseras", prefijo: "PUL" },
  { id: "aretes", nombre: "Aretes", prefijo: "ARE" },
  { id: "celulares", nombre: "Celulares", prefijo: "CEL" },
  { id: "anillos", nombre: "Anillos", prefijo: "ANI" },
  { id: "collares", nombre: "Collares", prefijo: "COL" },
];

export const productosSeed = [
  { codigo: "CAI-001", nombre: "Ballenas", categoriaId: "caimanes", precio: 11000, stock: 7, estado: "activo", fotos: [] },
  { codigo: "CAI-002", nombre: "Ballena azul", categoriaId: "caimanes", precio: 11000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "CAI-003", nombre: "Pez rojo", categoriaId: "caimanes", precio: 11000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "CAI-004", nombre: "Pez azul pequeño", categoriaId: "caimanes", precio: 11000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "CAI-005", nombre: "Delfín rosado pequeño", categoriaId: "caimanes", precio: 11000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "CAI-006", nombre: "Manzana", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-007", nombre: "Estrella mar", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-008", nombre: "Cangrejo amarillo", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-009", nombre: "Perro", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-010", nombre: "Pez largo", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-011", nombre: "Dona", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-012", nombre: "Moto", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CAI-013", nombre: "Rosado flor", categoriaId: "caimanes", precio: 11000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CIN-001", nombre: "Cinturón", categoriaId: "cinturones", precio: 55000, stock: 4, estado: "activo", fotos: [] },
  { codigo: "BOL-001", nombre: "Fuccia", categoriaId: "bolsos", precio: 60000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "BOL-002", nombre: "Blanco Fuccia", categoriaId: "bolsos", precio: 60000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "BOL-003", nombre: "Blanco Negro", categoriaId: "bolsos", precio: 60000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "PUL-001", nombre: "Colores variados", categoriaId: "pulseras", precio: 25000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "PUL-002", nombre: "Colores piedras", categoriaId: "pulseras", precio: 40000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "PUL-003", nombre: "Esferas y corazón", categoriaId: "pulseras", precio: 25000, stock: 5, estado: "activo", fotos: [] },
  { codigo: "PUL-004", nombre: "Marfil turquesa", categoriaId: "pulseras", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "PUL-005", nombre: "Marfil y Café", categoriaId: "pulseras", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "PUL-006", nombre: "Cilindros multicolores", categoriaId: "pulseras", precio: 38000, stock: 5, estado: "activo", fotos: [] },
  { codigo: "PUL-007", nombre: "Bloques multicolores", categoriaId: "pulseras", precio: 35000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "PUL-008", nombre: "Pulseras colores", categoriaId: "pulseras", precio: 28000, stock: 8, estado: "activo", fotos: [] },
  { codigo: "PUL-009", nombre: "Corazón Hongo", categoriaId: "pulseras", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "PUL-010", nombre: "Corazón tejido x4", categoriaId: "pulseras", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "PUL-011", nombre: "Flor x4", categoriaId: "pulseras", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-001", nombre: "Topos rayas", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-002", nombre: "Delfines", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-003", nombre: "Colgantes geométrico", categoriaId: "aretes", precio: 30000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-004", nombre: "Candonga verde", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-005", nombre: "Gotas", categoriaId: "aretes", precio: 16000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-006", nombre: "Topo abeja", categoriaId: "aretes", precio: 28000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-007", nombre: "Corazón peludo", categoriaId: "aretes", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-008", nombre: "Pez Koi", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-009", nombre: "Círculo verde", categoriaId: "aretes", precio: 17000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-010", nombre: "Gota Verde", categoriaId: "aretes", precio: 17000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-011", nombre: "Negro vetas", categoriaId: "aretes", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-012", nombre: "Corazón colores", categoriaId: "aretes", precio: 25000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-013", nombre: "Estrella mar grande", categoriaId: "aretes", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-014", nombre: "Abeja", categoriaId: "aretes", precio: 50000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-015", nombre: "Corazón plateado", categoriaId: "aretes", precio: 20000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-016", nombre: "Marfil y piedritas", categoriaId: "aretes", precio: 26000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-017", nombre: "Topos colores", categoriaId: "aretes", precio: 18000, stock: 4, estado: "activo", fotos: [] },
  { codigo: "ARE-018", nombre: "Topo dona", categoriaId: "aretes", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-019", nombre: "Langosta", categoriaId: "aretes", precio: 50000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-020", nombre: "Topos Grandes", categoriaId: "aretes", precio: 25000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-021", nombre: "Topo concha", categoriaId: "aretes", precio: 28000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-022", nombre: "Topo mariposa", categoriaId: "aretes", precio: 15000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-023", nombre: "Cangrejos", categoriaId: "aretes", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-024", nombre: "Hojas", categoriaId: "aretes", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-025", nombre: "Flor plata y ámbar", categoriaId: "aretes", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-026", nombre: "Panteras", categoriaId: "aretes", precio: 42000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-027", nombre: "Colgante turquesa", categoriaId: "aretes", precio: 20000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-028", nombre: "Corazón colgante", categoriaId: "aretes", precio: 48000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-029", nombre: "Tiburón", categoriaId: "aretes", precio: 38000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-030", nombre: "Peces", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-031", nombre: "Ranas", categoriaId: "aretes", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-032", nombre: "Bailarinas", categoriaId: "aretes", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-033", nombre: "Topos gota de agua", categoriaId: "aretes", precio: 10000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-034", nombre: "Candonga multicolor", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-035", nombre: "Gota tornasol", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-036", nombre: "Serpiente pequeña", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-037", nombre: "Candonga pequeña", categoriaId: "aretes", precio: 20000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-038", nombre: "Triángulo", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-039", nombre: "Círculo animal print", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-040", nombre: "Círculo oro", categoriaId: "aretes", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-041", nombre: "Estrella x3", categoriaId: "aretes", precio: 10000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-042", nombre: "Cebra", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-043", nombre: "Candonga color ele", categoriaId: "aretes", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-044", nombre: "Caballito Mar", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-045", nombre: "Oro perla azul", categoriaId: "aretes", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-046", nombre: "Earcuff colores", categoriaId: "aretes", precio: 8000, stock: 4, estado: "activo", fotos: [] },
  { codigo: "ARE-047", nombre: "Earcuff oro", categoriaId: "aretes", precio: 10000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-048", nombre: "Earcuff liso", categoriaId: "aretes", precio: 12000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-049", nombre: "Earcuff piedras", categoriaId: "aretes", precio: 18000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ARE-050", nombre: "Aretes perlas", categoriaId: "aretes", precio: 30000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "ARE-051", nombre: "Margaritas", categoriaId: "aretes", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ARE-052", nombre: "Flor roja", categoriaId: "aretes", precio: 35000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "CEL-001", nombre: "Cadena beige", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-002", nombre: "Llavero rosado celular", categoriaId: "celulares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-003", nombre: "Llavero flores", categoriaId: "celulares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-004", nombre: "Llavero corazón", categoriaId: "celulares", precio: 32000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-005", nombre: "Cadena negra", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-006", nombre: "Cadena plateada", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-007", nombre: "Cadena rosada", categoriaId: "celulares", precio: 60000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-008", nombre: "Cadena roja", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-009", nombre: "Llavero morado", categoriaId: "celulares", precio: 32000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-010", nombre: "Cadena estrellas", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-011", nombre: "Cadena perlas", categoriaId: "celulares", precio: 68000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "CEL-012", nombre: "Llavero rosado estrella", categoriaId: "celulares", precio: 32000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-001", nombre: "Corazón grande oro", categoriaId: "anillos", precio: 25000, stock: 9, estado: "activo", fotos: [] },
  { codigo: "ANI-002", nombre: "Anillo cangrejo", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-003", nombre: "Corazón plástico", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-004", nombre: "Anillo piedra", categoriaId: "anillos", precio: 32000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-005", nombre: "Anillo langosta", categoriaId: "anillos", precio: 26000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-006", nombre: "Anillo nube", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-007", nombre: "Anillo delgado rosaperla", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-008", nombre: "Anillo corazón beige", categoriaId: "anillos", precio: 38000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-009", nombre: "Anillo corazón vinotinto", categoriaId: "anillos", precio: 25000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-010", nombre: "Anillo corazón grande", categoriaId: "anillos", precio: 25000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-011", nombre: "Anillo 2 gotas", categoriaId: "anillos", precio: 25600, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-012", nombre: "Anillo pepa", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-013", nombre: "Anillo pepa pequeño blanco", categoriaId: "anillos", precio: 20000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-014", nombre: "Anillo flores", categoriaId: "anillos", precio: 25000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-015", nombre: "Anillo plateado", categoriaId: "anillos", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-016", nombre: "Anillo cuadro", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-017", nombre: "Anillo concha plata", categoriaId: "anillos", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "ANI-018", nombre: "Sol", categoriaId: "anillos", precio: 28000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "ANI-019", nombre: "Margarita", categoriaId: "anillos", precio: 28000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-001", nombre: "Azul cangrejo", categoriaId: "collares", precio: 65000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-002", nombre: "Blanco langosta", categoriaId: "collares", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-003", nombre: "Corazón forma pastel", categoriaId: "collares", precio: 42000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-004", nombre: "Piedra naturales", categoriaId: "collares", precio: 65000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-005", nombre: "Cangrejo lila", categoriaId: "collares", precio: 49000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-006", nombre: "Doble y corazón", categoriaId: "collares", precio: 70000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-007", nombre: "Cangrejo rosado", categoriaId: "collares", precio: 49000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-008", nombre: "Leopardo", categoriaId: "collares", precio: 72000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-009", nombre: "Rosado langosta", categoriaId: "collares", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-010", nombre: "Concha azul", categoriaId: "collares", precio: 55000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-011", nombre: "Colores langosta", categoriaId: "collares", precio: 50000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-012", nombre: "Cangrejo rosa lila", categoriaId: "collares", precio: 45000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-013", nombre: "Blanco hongo", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-014", nombre: "Blanco huevo frito", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-015", nombre: "Mar y flores rojo", categoriaId: "collares", precio: 38000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-016", nombre: "Canicas negro", categoriaId: "collares", precio: 55000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-017", nombre: "Canicas", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-018", nombre: "Morado perro", categoriaId: "collares", precio: 42000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-019", nombre: "Perlas invisibles", categoriaId: "collares", precio: 25000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-020", nombre: "Perlas corazones colores", categoriaId: "collares", precio: 40000, stock: 6, estado: "activo", fotos: [] },
  { codigo: "COL-021", nombre: "Perla amarilla margarita", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-022", nombre: "Perla Sol", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-023", nombre: "Perla verde margarita", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-024", nombre: "Margaritas rosado", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-025", nombre: "Collar corazón perla", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-026", nombre: "Shoker pastel flores", categoriaId: "collares", precio: 35000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-027", nombre: "Collar flor margarita", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-028", nombre: "Flor corazón", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-029", nombre: "Papas café corazón", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-030", nombre: "Pepas negras y doradas", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-031", nombre: "Pepas grandes corazón", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-032", nombre: "Perlas corazón amarillo", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-033", nombre: "Perlas corazones rojos", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-034", nombre: "Collar Pepas colores", categoriaId: "collares", precio: 28000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-035", nombre: "Shocker corazón rosado", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-036", nombre: "Shocker estrella corazones", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-037", nombre: "Collar corazón anatómico", categoriaId: "collares", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-038", nombre: "Rosado corazón", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-039", nombre: "Sol", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-040", nombre: "Corazón blanco + topos", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-041", nombre: "Corazón anatómico cadena", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-042", nombre: "Shocker pez", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-043", nombre: "Cadena círculo estrella", categoriaId: "collares", precio: 28000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-044", nombre: "Cadena corazón", categoriaId: "collares", precio: 30000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-045", nombre: "Corazón azul perlado", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-046", nombre: "Shocker corazones dorado rojo", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-047", nombre: "Collar oso", categoriaId: "collares", precio: 30000, stock: 6, estado: "activo", fotos: [] },
  { codigo: "COL-048", nombre: "Corazón café", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-049", nombre: "Flor cadena", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-050", nombre: "Margarita cadena", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-051", nombre: "Cadena corazón", categoriaId: "collares", precio: 40000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-052", nombre: "Cangrejo", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-053", nombre: "Arcoíris", categoriaId: "collares", precio: 35000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-054", nombre: "Cadena varios corazones", categoriaId: "collares", precio: 35000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-055", nombre: "Perla margarita", categoriaId: "collares", precio: 40000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-056", nombre: "Azul cangrejo dorado", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-057", nombre: "Blanco leopardo", categoriaId: "collares", precio: 62000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-058", nombre: "Doble Heart", categoriaId: "collares", precio: 50000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-059", nombre: "Manchas café y dorado", categoriaId: "collares", precio: 50000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-060", nombre: "Palmeras", categoriaId: "collares", precio: 42000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-061", nombre: "Cangrejo gigante", categoriaId: "collares", precio: 120000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-062", nombre: "Banano", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-063", nombre: "Blanco langosta azul", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-064", nombre: "Rosa heart", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-065", nombre: "Azul manta raya", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-066", nombre: "Helado", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-067", nombre: "Piedras ámbar", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-068", nombre: "Marfil tortuga", categoriaId: "collares", precio: 35000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-069", nombre: "Eslabon gigante", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-070", nombre: "Muchos corazones", categoriaId: "collares", precio: 32000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-071", nombre: "Mar estrella", categoriaId: "collares", precio: 28000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-072", nombre: "Azul mar pez", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-073", nombre: "Peces", categoriaId: "collares", precio: 40000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-074", nombre: "Corazón y Pepas", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-075", nombre: "Dorado y corazón", categoriaId: "collares", precio: 42000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-076", nombre: "Hongos", categoriaId: "collares", precio: 85000, stock: 5, estado: "activo", fotos: [] },
  { codigo: "COL-077", nombre: "Camarón", categoriaId: "collares", precio: 85000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-078", nombre: "Eslabón pequeño", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-079", nombre: "Eslabón grande", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-080", nombre: "Cebra", categoriaId: "collares", precio: 85000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-081", nombre: "Cangrejo mini rosa", categoriaId: "collares", precio: 32000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-082", nombre: "Mar pez rojo", categoriaId: "collares", precio: 32000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-083", nombre: "Muchos corazones dorados", categoriaId: "collares", precio: 38000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-084", nombre: "Nude marino", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-085", nombre: "Azul mantaraya", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-086", nombre: "Eslabones", categoriaId: "collares", precio: 62000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-087", nombre: "Plateado y pez", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-088", nombre: "Corazón con forma", categoriaId: "collares", precio: 42000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-089", nombre: "Corazón microperla", categoriaId: "collares", precio: 42000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-090", nombre: "Tortugas", categoriaId: "collares", precio: 42000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-091", nombre: "Corazón textura", categoriaId: "collares", precio: 55000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-092", nombre: "Mariquitas", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-093", nombre: "Cangrejo mediano", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-094", nombre: "Corazón anatómico", categoriaId: "collares", precio: 50000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-095", nombre: "Colores medusa", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-096", nombre: "Corazón minimed", categoriaId: "collares", precio: 35000, stock: 4, estado: "activo", fotos: [] },
  { codigo: "COL-097", nombre: "Delgado corazón", categoriaId: "collares", precio: 40000, stock: 4, estado: "activo", fotos: [] },
  { codigo: "COL-098", nombre: "Mar azul", categoriaId: "collares", precio: 28000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-099", nombre: "Piedras naturales", categoriaId: "collares", precio: 65000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-100", nombre: "Hojas y flores", categoriaId: "collares", precio: 65000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-101", nombre: "Perla rosada corazón igo", categoriaId: "collares", precio: 38000, stock: 3, estado: "activo", fotos: [] },
  { codigo: "COL-102", nombre: "Mar azul dorado", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-103", nombre: "Pez Colombia", categoriaId: "collares", precio: 28000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-104", nombre: "Corazón blanco perla verde", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-105", nombre: "Perla pequeña corazón rojo", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-106", nombre: "Invisibles", categoriaId: "collares", precio: 25000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-107", nombre: "Perla roja cangrejo", categoriaId: "collares", precio: 30000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-108", nombre: "Corazón café", categoriaId: "collares", precio: 40000, stock: 2, estado: "activo", fotos: [] },
  { codigo: "COL-109", nombre: "Rosa pastel cangrejo", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-110", nombre: "Corazón rojo Pepas amarillas", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-111", nombre: "Perlas corazón colores", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-112", nombre: "Honguitos colores", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-113", nombre: "Perlas pez", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-114", nombre: "Estrella plateados", categoriaId: "collares", precio: 40000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-115", nombre: "Pepas corazón morado", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-116", nombre: "Corazones pequeños cadena", categoriaId: "collares", precio: 20000, stock: 1, estado: "activo", fotos: [] },
  { codigo: "COL-117", nombre: "Estrella mar tortuga", categoriaId: "collares", precio: 38000, stock: 1, estado: "activo", fotos: [] },
];
